version: '2'

services:
  haproxy:
    build: ./haproxy/.
    ports:
      - '8080:8080'
      
  webserver1:
    build: webserver1/.
    ports:
      - '3001:80'

  webserver2:
    build: webserver2/.
    ports:
      - '3002:80'